export const mapData = [
  {
    id: 1,
    title: "로터스",
    titleSlice: ["ㄹ", "로", "롵Q", "로터", "로텃B", "로터스"],
    desc: "고대의 힘을 내뿜는 별 매개체를 간직한 신비로운 건축물입니다. 돌로 된 거대한 문은 다양한 이동 경로를 제공하며 신비로운 지점 3개로의 길을 열어줍니다.",
    titleimg: "/images/map/01_Lotus/Lotus01.png",
    subimg: ["/images/map/01_Lotus/Lotus02.jpg", "/images/map/01_Lotus/Lotus03.jpg", "/images/map/01_Lotus/Lotus04.jpg", "/images/map/01_Lotus/Lotus05.jpg"],
  },
  {
    id: 2,
    title: "펄",
    titleSlice: ["ㅍ", "P", "퍼", "G", "펄"],
    desc: "공격팀은 역동적인 수중 도시의 2개 지점으로 나뉜 맵에서 수비팀을 압박합니다. 펄은 기계적 요소가 없는 지형 기반의 맵입니다. 협소한 중앙과 양쪽의 긴 구역으로 이루어진 오메가 지구의 첫 번째 맵에서 전투를 벌이세요.",
    titleimg: "/images/map/02_Pearl/Pearl01.png",
    subimg: ["/images/map/02_Pearl/Pearl02.jpg", "/images/map/02_Pearl/Pearl03.jpg", "/images/map/02_Pearl/Pearl04.jpg", "/images/map/02_Pearl/Pearl05.jpg"],
  },
  {
    id: 3,
    title: "프랙처",
    titleSlice: ["ㅍ", "프", "플B", "프래", "프랙K", "프랙ㅊ", "프랙처"],
    desc: "레디어나이트 실험 실패로 파괴된 일급 비밀 연구 시설입니다. 수비팀의 전략은 맵처럼 두 갈래로 나누어집니다. 공격팀의 영역에서 맞붙거나 위기에 대비하여 공격을 견디세요.",
    titleimg: "/images/map/03_Fracture/Fracture01.png",
    subimg: ["/images/map/03_Fracture/Fracture02.jpg", "/images/map/03_Fracture/Fracture03.jpg", "/images/map/03_Fracture/Fracture04.jpg", "/images/map/03_Fracture/Fracture05.jpg"],
  },
  {
    id: 4,
    title: "브리즈",
    titleSlice: ["ㅂ", "브", "브L", "블L", "브리", "브리A", "브맂", "브맂T", "브리즈"],
    desc: "열대 파라다이스의 역사적 유적과 해변 동굴의 경치를 만끽해보세요. 하지만 엄호가 필요할 겁니다. 탁 트인 넓은 공간에서 원거리 교전이 펼쳐지니까요. 측면 공격에 잘 대비한다면 승리에 한 걸음 다가갈 수 있을 것입니다.",
    titleimg: "/images/map/04_Breeze/Breeze01.png",
    subimg: ["/images/map/04_Breeze/Breeze02.jpg", "/images/map/04_Breeze/Breeze03.jpg", "/images/map/04_Breeze/Breeze04.jpg", "/images/map/04_Breeze/Breeze05.jpg"],
  },
  {
    id: 5,
    title: "아이스박스",
    titleSlice: ["ㅇ", "아", "아A", "앙", "아이", "아잇V", "아이스", "아이습C", "아이스바", "아이스박", "아이스밗GH", "아이스박스"],
    desc: "다음 전장은 혹한 지대에 위치한 킹덤의 비밀 발굴 현장입니다. 눈과 쇠붙이로 둘러싸인 스파이크 설치 지점에서는 전후좌우로 능숙하게 교전하는 능력이 필수죠. 집라인을 이용한 기습 공격으로 적의 허를 찔러보세요.",
    titleimg: "/images/map/05_Icebox/Icebox01.png",
    subimg: ["/images/map/05_Icebox/Icebox02.jpg", "/images/map/05_Icebox/Icebox03.jpg", "/images/map/05_Icebox/Icebox04.jpg", "/images/map/05_Icebox/Icebox05.jpg"],
  },
  {
    id: 6,
    title: "바인드",
    titleSlice: ["ㅂ", "바", "방B", "바이", "바인H", "바인ㄷ", "바인드"],
    desc: "두 지점으로 구성되며 중간 지점이 없어 왼쪽 또는 오른쪽을 선택해야 합니다. 양쪽 지점에는 공격팀을 위한 지름길과 한쪽으로만 이동할 수 있는 순간이동기 한 쌍이 있어 측면 공격에 활용할 수 있습니다.",
    titleimg: "/images/map/06_Bind/Bind01.png",
    subimg: ["/images/map/06_Bind/Bind02.jpg", "/images/map/06_Bind/Bind03.jpg", "/images/map/06_Bind/Bind04.jpg", "/images/map/06_Bind/Bind05.jpg"],
  },
  {
    id: 7,
    title: "헤이븐",
    titleSlice: ["ㅎ", "헤", "헹H", "헤이", "헤입K", "헤이브", "헤이븐"],
    desc: "잊혀진 수도원 아래에서 세 지점을 장악하기 위한 요원들의 전투가 활발히 벌어집니다. 장악해야 할 지역이 더 많지만, 수비팀이 추가 지역을 이용해 공격적인 압박을 가할 수 있습니다.",
    titleimg: "/images/map/07_Haven/Haven01.png",
    subimg: ["/images/map/07_Haven/Haven02.jpg", "/images/map/07_Haven/Haven03.jpg", "/images/map/07_Haven/Haven04.jpg", "/images/map/07_Haven/Haven05.jpg"],
  },
  {
    id: 8,
    title: "스플릿",
    titleSlice: ["ㅅ", "스", "슾J", "스프", "스플R", "스플ㄹ", "스플리", "스플릿"],
    desc: "멀리 가려면 위로 이동해야 합니다. 높이 솟아오른 중앙 구역이 두 지점을 나누고 있어 줄사다리 두 개를 이용해 재빨리 움직일 수 있죠. 각 지점에는 장악에 아주 중요한 탑이 세워져 있습니다. 속수무책으로 당하지 않으려면 꼭 위쪽을 확인하세요.",
    titleimg: "/images/map/08_Split/Split01.png",
    subimg: ["/images/map/08_Split/Split02.jpg", "/images/map/08_Split/Split03.jpg", "/images/map/08_Split/Split04.jpg", "/images/map/08_Split/Split05.jpg"],
  },
  {
    id: 9,
    title: "어센트",
    titleSlice: ["ㅇ", "어", "엇A", "어세", "어센W", "어센ㅌ", "어센트"],
    desc: "어센트에서는 소규모 진지전과 소모전을 벌일 수 있는 개방 구역을 중심으로 두 지점이 나뉘어 있습니다. 각 지점은 해체 불가능한 폭탄 문으로 수비를 강화할 수 있으며, 일단 문이 닫히면 문을 파괴하거나 다른 길을 찾아야 합니다. 가능한 한 많은 지역을 지키세요.",
    titleimg: "/images/map/09_Ascent/Ascent01.png",
    subimg: ["/images/map/09_Ascent/Ascent02.jpg", "/images/map/09_Ascent/Ascent03.jpg", "/images/map/09_Ascent/Ascent04.jpg", "/images/map/09_Ascent/Ascent05.jpg"],
  },
];
