export const agentData = [
  {
    id: 1,
    name: "제트",
    role: "타격대",
    roleimg: "",
    desc: "한국 출신으로 신속하고 은밀하게 움직이는 제트는 다른 사람이라면 엄두도 못 낼 위험한 일도 마다하지 않습니다. 교전이 벌어질 때면 어김없이 상대보다 뛰어난 능력을 통해 기습적으로 공격합니다.",
    agentimg: "/images/agent/HeroImages/Jett/Jett.png",
    skill: ["Q - 상승 기류", "E - 순풍", "C - 연막 폭발", "X - 칼날 폭풍"],
    skillimg: ["/images/agent/HeroImages/Jett/Jett_Q.png", "/images/agent/HeroImages/Jett/Jett_E.png", "/images/agent/HeroImages/Jett/Jett_C.png", "/images/agent/HeroImages/Jett/Jett_X.png"],
    skillExplan: [
      "제트가 즉시 높이 날아오릅니다.",
      "활성화 시 일정 시간 동안 돌풍을 준비합니다. 돌풍을 다시 사용하면 제트가 이동 방향으로 빠르게 이동합니다. 제트가 가만히 서 있을 경우에는 앞으로 빠르게 이동합니다. 순풍 충전량은 2킬마다 초기화됩니다.",
      "표면에 닿아 충격을 받으면 구름으로 팽창해 잠시 시야를 가리는 투사체를 즉시 던집니다. 스킬 키를 길게 누르면 연기가 조준점 방향으로 휘어집니다.",
      "명중률이 높은 투척용 단검을 장착합니다. 발사하면 단검 하나를 던지며, 처치 시 단검을 충전합니다. 보조 공격 시 남은 단검을 전부 던집니다. 이 경우 처치 시 단검이 충전되지 않습니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Jett/Jett_Q.mp4", "/images/agent/HeroImages/Jett/Jett_E.mp4", "/images/agent/HeroImages/Jett/Jett_C.mp4", "/images/agent/HeroImages/Jett/Jett_X.mp4"],
  },
  ,
  {
    id: 2,
    name: "레이즈",
    role: "타격대",
    desc: "브라질에서 온 레이즈는 화끈한 성격으로 커다란 총기를 휘두릅니다. 그녀의 저돌적인 전투 스타일은 엄폐 중인 적을 몰아내는 데 적합하며 대량의 폭발물로 좁은 지역을 초토화합니다.",
    agentimg: "/images/agent/HeroImages/Raze/Raze.png",
    skill: ["Q - 폭발 팩", "E - 페인트탄", "C - 폭발 봇", "X - 대미 장식"],
    skillimg: ["/images/agent/HeroImages/Raze/Raze_Q.png", "/images/agent/HeroImages/Raze/Raze_E.png", "/images/agent/HeroImages/Raze/Raze_C.png", "/images/agent/HeroImages/Raze/Raze_X.png"],
    skillExplan: [
      "표면에 부착되는 폭발 팩을 던집니다. 부착 후 다시 사용하면 팩이 폭발하며 적중한 대상에게 피해를 입히고 밀어냅니다. 레이즈는 이 스킬로 인한 피해를 입지 않지만 멀리 날아갈 경우 추락 피해는 입을 수 있습니다.",
      "집속탄을 장착합니다. 발사하면 집속탄을 던집니다. 집속탄은 피해를 입히고 여러 개의 자탄을 퍼뜨립니다. 자탄은 각각의 범위 내에 있는 모든 대상에게 피해를 입힙니다. 보조 공격 시 높이 던집니다. 페인트탄 충전량은 2킬마다 초기화됩니다.",
      "폭발 봇을 장착합니다. 발사하면 폭발 봇이 지면에서 일직선으로 이동하며 벽을 만나면 튕겨 나옵니다. 폭발 봇의 정면 원뿔형 시야 안에 적이 포착되면 해당 적에게 돌진하며 폭발해 치명적인 피해를 입힙니다.",
      "로켓 발사기를 장착합니다. 발사하면 충돌 시 대량의 범위 피해를 입히는 로켓을 발사합니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Raze/Raze_Q.mp4", "/images/agent/HeroImages/Raze/Raze_E.mp4", "/images/agent/HeroImages/Raze/Raze_C.mp4", "/images/agent/HeroImages/Raze/Raze_X.mp4"],
  },
  {
    id: 3,
    name: "브리치",
    role: "척후대",
    desc: "스웨덴 출신의 생체병기 브리치는 강력한 역학적 폭발을 이용해 적진을 돌파합니다. 브리치의 강력한 피해량과 교란술은 아군이 굳이 공정한 전투를 할 필요가 없게 만들죠.",
    agentimg: "/images/agent/HeroImages/Breach/Breach.png",
    skill: ["Q - 섬광 폭발", "E - 균열", "C - 여진", "X - 지진 강타"],
    skillimg: ["/images/agent/HeroImages/Breach/Breach_Q.png", "/images/agent/HeroImages/Breach/Breach_E.png", "/images/agent/HeroImages/Breach/Breach_C.png", "/images/agent/HeroImages/Breach/Breach_X.png"],
    skillExplan: [
      "실명탄을 장착합니다. 발사하면 벽을 통과하고 빠르게 효과가 발생하는 폭발을 일으켜 섬광을 본 모든 플레이어를 실명시킵니다.",
      "지진파를 장착합니다. 발사를 길게 누르면 사거리가 늘어납니다. 키를 떼면 지진파를 날려 경로상에 있는 적과 대상 범위 내의 모든 적을 멍하게 합니다.",
      "융합 에너지탄을 장착합니다. 발사하면 벽을 통과하고 느리게 효과가 발생하는 폭발을 일으켜 대상 범위 내의 모든 적에게 큰 피해를 입힙니다.",
      "지진탄을 장착합니다. 발사하면 모든 지형을 통과하는 지진 파동을 날려 경로상에 있는 모든 적을 멍하게 하고 공중으로 띄웁니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Breach/Breach_Q.mp4", "/images/agent/HeroImages/Breach/Breach_E.mp4", "/images/agent/HeroImages/Breach/Breach_C.mp4", "/images/agent/HeroImages/Breach/Breach_X.mp4"],
  },
  {
    id: 4,
    name: "오멘",
    role: "전략가",
    desc: "기억의 유령 오멘은 그림자 속에서 적들을 사냥합니다. 적들의 눈을 멀게 하고 전장 어느 곳이든 이동하며 피해망상을 일으키는 능력 때문에 상대는 다음 공격을 예측할 수 없어 혼란에 빠지게 됩니다.",
    agentimg: "/images/agent/HeroImages/Omen/Omen.png",
    skill: ["Q - 피해망상", "E - 어둠의 장막", "C - 어둠의 발자국", "X - 그림자 습격"],
    skillimg: ["/images/agent/HeroImages/Omen/Omen_Q.png", "/images/agent/HeroImages/Omen/Omen_E.png", "/images/agent/HeroImages/Omen/Omen_C.png", "/images/agent/HeroImages/Omen/Omen_X.png"],
    skillExplan: [
      "실명 구슬을 장착합니다. 발사하면 앞으로 던져 구슬에 닿은 모든 플레이어의 가시거리와 청력을 잠시 감소시킵니다. 이 투사체는 벽을 통과할 수 있습니다.",
      "그림자 구슬을 장착하고 다른 차원의 세계로 들어가 구슬을 조준합니다. 스킬 키를 누르면 표시한 위치에 그림자 구슬을 던져 한동안 시야를 차단하는 그림자 영역을 생성합니다. 발사를 길게 누르면 표시 위치를 더 멀리 옮깁니다. 보조 공격을 길게 누르면 표시 위치를 더 가까이 옮깁니다. 재장전을 누르면 기본 조준점을 끄고 켭니다.",
      "어둠의 발자국 스킬을 장착하고 사거리를 표시합니다. 발사하면 짧은 정신 집중 후 표시한 위치로 순간이동합니다.",
      "전술 지도를 장착합니다. 발사하면 선택한 위치로 순간이동을 시작합니다. 순간이동 중에는 오멘이 그림자로 나타나며 이때 적이 그림자를 파괴하면 순간이동이 취소됩니다. 장착을 누르면 오멘이 순간이동을 취소합니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Omen/Omen_Q.mp4", "/images/agent/HeroImages/Omen/Omen_E.mp4", "/images/agent/HeroImages/Omen/Omen_C.mp4", "/images/agent/HeroImages/Omen/Omen_X.mp4"],
  },
  {
    id: 5,
    name: "브림스톤",
    role: "전략가",
    desc: "미국 출신 브림스톤은 궤도 무기를 활용해 아군에게 유리하도록 전투를 이끕니다. 멀리서 정확하게 다양한 수단으로 팀을 보조하는 능력 덕분에 그는 최고의 야전 사령관으로 불립니다.",
    agentimg: "/images/agent/HeroImages/Brimstone/Brimstone.png",
    skill: ["Q - 소이탄", "E - 공중 연막", "C - 자극제 신호기", "X - 궤도 일격"],
    skillimg: ["/images/agent/HeroImages/Brimstone/Brimstone_Q.png", "/images/agent/HeroImages/Brimstone/Brimstone_E.png", "/images/agent/HeroImages/Brimstone/Brimstone_C.png", "/images/agent/HeroImages/Brimstone/Brimstone_X.png"],
    skillExplan: [
      "소이탄 발사기를 장착합니다. 발사하면 바닥에 떨어졌을 때 폭발하는 소이탄을 날려 적에게 피해를 입히는 화염 구역을 생성합니다. 생성된 구역은 긴 시간 유지됩니다.",
      "전술 지도를 장착합니다. 발사하면 브림스톤의 연막을 퍼뜨릴 위치를 설정합니다. 보조 공격 시 위치 확정 후 연막을 날려 한동안 선택한 지역의 시야를 차단합니다.",
      "자극제 신호기를 장착합니다. 발사하면 브림스톤 앞에 자극제 신호기를 던집니다. 신호기가 떨어진 곳에는 플레이어에게 속사와 속도 상승 효과를 부여하는 영역이 생성됩니다.",
      "전술 지도를 장착합니다. 발사하면 선택한 위치에 궤도 일격 레이저를 쏘아 해당 영역에 있는 플레이어에게 큰 지속 피해를 입힙니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Brimstone/Brimstone_Q.mp4", "/images/agent/HeroImages/Brimstone/Brimstone_E.mp4", "/images/agent/HeroImages/Brimstone/Brimstone_C.mp4", "/images/agent/HeroImages/Brimstone/Brimstone_X.mp4"],
  },
  {
    id: 6,
    name: "피닉스",
    role: "타격대",
    desc: "영국 출신 피닉스의 탁월한 능력은 전장을 섬광탄과 불꽃으로 수놓는 전투 스타일에서 비롯됩니다. 팀의 지원이 있든 없든 피닉스는 자신만의 방식으로 전투를 이끌어갑니다.",
    agentimg: "/images/agent/HeroImages/Phoenix/Phoenix.png",
    skill: ["Q - 커브볼", "E - 뜨거운 손", "C - 불길", "X - 역습"],
    skillimg: ["/images/agent/HeroImages/Phoenix/Phoenix_Q.png", "/images/agent/HeroImages/Phoenix/Phoenix_E.png", "/images/agent/HeroImages/Phoenix/Phoenix_C.png", "/images/agent/HeroImages/Phoenix/Phoenix_X.png"],
    skillExplan: [
      "던지면 휘어져 날아간 후 곧 폭발하는 섬광 구슬을 장착합니다. 발사하면 섬광 구슬이 왼쪽으로 휘어지며 폭발합니다. 이때 구슬을 바라보는 플레이어는 전부 실명합니다. 보조 공격 시 섬광 구슬이 오른쪽으로 휘어집니다.",
      "화염구를 장착합니다. 발사하면 일정 시간이 지나거나 땅에 닿은 후 폭발하는 화염구를 던집니다. 폭발하는 지점에는 일정 시간 유지되는 화염 구역이 생성되어 적에게 피해를 입힙니다. 자신이 던진 화염구에 닿으면 HP가 회복됩니다.",
      "화염 장벽을 장착합니다. 발사하면 앞으로 이동하는 여러 개의 화염을 일렬로 생성하여 시야를 차단하고 통과하는 적 플레이어에게 피해를 입히는 화염 장벽을 생성합니다. 발사를 길게 누르면 조준점 방향으로 장벽 궤적을 바꿉니다. 자신이 발사한 화염 장벽에 닿으면 HP가 회복됩니다.",
      "즉시 피닉스의 위치에 표식을 놓습니다. 스킬 사용 도중 죽거나 지속시간이 끝나면 해당 위치에서 최대 체력으로 부활합니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Phoenix/Phoenix_Q.mp4", "/images/agent/HeroImages/Phoenix/Phoenix_E.mp4", "/images/agent/HeroImages/Phoenix/Phoenix_C.mp4", "/images/agent/HeroImages/Phoenix/Phoenix_X.mp4"],
  },
  {
    id: 7,
    name: "세이지",
    role: "감시자",
    desc: "중국에서 온 세이지는 어디에서든 자신과 아군이 안전할 수 있도록 능력을 발휘합니다. 쓰러진 아군을 부활시키거나 공격적인 압박을 피할 수 있는 능력으로 지옥 같은 전투에서 고요한 중심이 되어 줍니다.",
    agentimg: "/images/agent/HeroImages/Sage/Sage.png",
    skill: ["Q - 둔화 구슬", "E - 회복 구슬", "C - 장벽 구슬", "X - 부활"],
    skillimg: ["/images/agent/HeroImages/Sage/Sage_Q.png", "/images/agent/HeroImages/Sage/Sage_E.png", "/images/agent/HeroImages/Sage/Sage_C.png", "/images/agent/HeroImages/Sage/Sage_X.png"],
    skillExplan: [
      "둔화 구슬을 장착합니다. 발사하면 땅에 닿은 후 폭발하여 일정 시간 동안 둔화 영역을 생성하는 구슬을 던집니다. 둔화 영역에 있는 플레이어는 속도가 느려집니다.",
      "회복 구슬을 장착합니다. 피해를 입은 아군을 조준한 후 발사하면 해당 아군이 서서히 체력을 회복합니다. 세이지가 피해를 입었을 때 보조 공격 시 자신의 체력을 서서히 회복합니다.",
      "장벽 구슬을 장착합니다. 발사하면 단단한 장벽을 설치합니다. 보조 공격시 장벽이 회전합니다.",
      "부활 스킬을 장착합니다. 죽은 아군을 조준한 후 발사하면 해당 아군이 부활하기 시작합니다. 짧은 정신 집중이 끝나면 아군이 최대 체력으로 되살아납니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Sage/Sage_Q.mp4", "/images/agent/HeroImages/Sage/Sage_E.mp4", "/images/agent/HeroImages/Sage/Sage_C.mp4", "/images/agent/HeroImages/Sage/Sage_X.mp4"],
  },
  {
    id: 8,
    name: "소바",
    role: "척후대",
    desc: "겨울이 끝없이 이어지는 러시아 툰드라 지대에서 온 소바는 적들을 추적하고 발견하는 능력이 뛰어나며 정밀하면서도 무자비하게 적을 섬멸합니다. 직접 제작한 활과 뛰어난 정찰 스킬은 숨어 있는 적도 놓치지 않습니다.",
    agentimg: "/images/agent/HeroImages/Sova/Sova.png",
    skill: ["Q - 충격 화살", "E - 정찰용 화살", "C - 올빼미 드론", "X - 사냥꾼의 분노"],
    skillimg: ["/images/agent/HeroImages/Sova/Sova_Q.png", "/images/agent/HeroImages/Sova/Sova_E.png", "/images/agent/HeroImages/Sova/Sova_C.png", "/images/agent/HeroImages/Sova/Sova_X.png"],
    skillExplan: [
      "충격 화살을 발사하는 활을 장착합니다. 발사하면 충돌 시 폭발하여 주변 플레이어에게 피해를 입히는 화살을 전방으로 날립니다. 발사를 길게 누르면 화살의 사거리가 늘어납니다. 보조 공격 시 화살이 최대 두 번 더 튕깁니다.",
      "정찰 화살을 발사하는 활을 장착합니다. 발사하면 정찰 화살을 전방으로 날려 화살이 꽂힌 곳을 기준으로 모습이 드러난 주변 적의 위치를 표시합니다. 적이 이 화살을 파괴할 수 있습니다. 발사를 길게 누르면 화살의 사거리가 늘어납니다. 보조 공격 시 화살이 최대 두 번 더 튕깁니다.",
      "올빼미 드론을 장착합니다. 발사하면 드론을 날려 조종합니다. 드론을 조종하는 동안 발사를 누르면 표식용 다트가 발사됩니다. 다트에 맞은 플레이어는 위치가 드러납니다.",
      "벽을 관통하는 에너지 3개를 장거리로 발사하는 활을 장착합니다. 발사하면 전방에 일직선상으로 에너지를 날려 닿은 적에게 피해를 입히고 위치를 드러냅니다. 스킬 지속시간이 활성화된 상태에서 최대 두 번 더 다시 사용할 수 있습니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Sova/Sova_Q.mp4", "/images/agent/HeroImages/Sova/Sova_E.mp4", "/images/agent/HeroImages/Sova/Sova_C.mp4", "/images/agent/HeroImages/Sova/Sova_X.mp4"],
  },
  {
    id: 9,
    name: "바이퍼",
    role: "전략가",
    desc: "미국 출신 화학자 바이퍼는 다양한 화학 무기로 전장을 장악하고 적의 시야를 차단합니다. 화학 공격으로부터 살아남는다고 해도 바이퍼의 심리전에 놀아날 뿐입니다.",
    agentimg: "/images/agent/HeroImages/Viper/Viper.png",
    skill: ["Q - 독성 연기", "E - 독성 장막", "C - 뱀 이빨", "X - 독사의 구덩이"],
    skillimg: ["/images/agent/HeroImages/Viper/Viper_Q.png", "/images/agent/HeroImages/Viper/Viper_E.png", "/images/agent/HeroImages/Viper/Viper_C.png", "/images/agent/HeroImages/Viper/Viper_X.png"],
    skillExplan: [
      "가스 방사기를 장착합니다. 발사하면 라운드 내내 유지되는 방사기를 던집니다. 스킬을 다시 사용하면 연료를 소모해 독성 가스 구름을 만듭니다. 이 스킬은 여러 번 재사용이 가능하여 주운 후 다시 배치할 수 있습니다.",
      "지형지물을 관통하는 가스 방사기 발사기를 장착합니다. 발사하면 여러 개의 가스 방사기를 일렬로 길게 배치합니다. 스킬을 다시 사용하면 연료를 소모해 높은 독성 연기 장벽을 생성합니다. 이 스킬은 여러 번 재사용이 가능합니다.",
      "화학 물질 발사기를 장착합니다. 발사하면 바닥에 떨어졌을 때 폭발하는 통을 날립니다. 통은 폭발하며 적에게 약화를 적용하고 피해를 입히는 화학 물질 지역을 일정 시간동안 생성합니다.",
      "화학 물질 분사기를 장착합니다. 발사하면 사방으로 화학 물질 연기를 분사해 안에 있는 플레이어의 가시거리와 최대 체력을 감소시키는 거대 연기를 생성합니다. 스킬 키를 길게 누르면 연기가 일찍 사라집니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Viper/Viper_Q.mp4", "/images/agent/HeroImages/Viper/Viper_E.mp4", "/images/agent/HeroImages/Viper/Viper_C.mp4", "/images/agent/HeroImages/Viper/Viper_X.mp4"],
  },
  {
    id: 10,
    name: "사이퍼",
    role: "감시자",
    desc: "걸어 다니는 감시망이라고도 할 수 있는 모로코 출신의 정보 브로커 사이퍼는 적의 움직임과 정보를 끊임없이 감시합니다. 어떤 비밀이나 속임수를 감추고 있든 끈질기고 날카로운 사이퍼의 시선을 피할 방법은 없습니다.",
    agentimg: "/images/agent/HeroImages/Cypher/Cypher.png",
    skill: ["Q - 사이버 감옥", "E - 스파이캠", "C - 함정", "X - 신경 절도"],
    skillimg: ["/images/agent/HeroImages/Cypher/Cypher_Q.png", "/images/agent/HeroImages/Cypher/Cypher_E.png", "/images/agent/HeroImages/Cypher/Cypher_C.png", "/images/agent/HeroImages/Cypher/Cypher_X.png"],
    skillExplan: [
      "사이버 감옥을 장착합니다. 발사하면 사이퍼 앞에 사이버 감옥을 던집니다. 활성화하면 시야를 차단하는 구역이 생성됩니다.",
      "스파이캠을 장착합니다. 발사하면 지정 위치에 스파이캠을 설치합니다. 스킬을 다시 사용하면 카메라 화면을 조작할 수 있습니다. 카메라를 조작하는 동안 발사를 누르면 표식용 다트가 발사됩니다. 다트에 맞은 플레이어는 위치가 드러납니다.",
      "함정을 장착합니다. 발사하면 지정 위치에 파괴 가능한 위장 함정을 설치하여 설치 위치와 반대쪽 벽을 연결하는 선을 생성합니다. 함정을 넘어가는 적 플레이어는 제때 장치를 파괴하지 않으면 잠시 후 속박되어 위치가 드러나며 멍해집니다. 이 스킬은 회수하여 다시 설치할 수 있습니다.",
      "즉시 대상으로 지정된 사망한 적 플레이어에게 사용해 적 팀의 정보를 다운로드합니다. 잠시 후 생존한 모든 적 플레이어의 위치가 두 번 드러납니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Cypher/Cypher_Q.mp4", "/images/agent/HeroImages/Cypher/Cypher_E.mp4", "/images/agent/HeroImages/Cypher/Cypher_C.mp4", "/images/agent/HeroImages/Cypher/Cypher_X.mp4"],
  },
  {
    id: 11,
    name: "레이나",
    role: "타격대",
    desc: "멕시코 중심부에서 태어난 레이나는 일대일 전투에 탁월하며 적을 처치할 때마다 강력해진다. 그녀의 능력은 온전히 전투 실력에만 좌우된다.",
    agentimg: "/images/agent/HeroImages/Reyna/Reyna.png",
    skill: ["Q - 포식", "E - 무시", "C - 눈총", "X - 여제"],
    skillimg: ["/images/agent/HeroImages/Reyna/Reyna_Q.png", "/images/agent/HeroImages/Reyna/Reyna_E.png", "/images/agent/HeroImages/Reyna/Reyna_C.png", "/images/agent/HeroImages/Reyna/Reyna_X.png"],
    skillExplan: [
      "즉시 근처에 있는 영혼 구슬을 흡수하여 짧은 시간 동안 순식간에 체력을 회복합니다. 이 스킬로 회복한 체력이 100을 넘어가면 초과분이 생기며 초과분은 시간이 흐르면서 사라집니다. 여제가 활성화 시 이 스킬이 자동으로 사용되며 영혼 구슬을 흡수하지 않습니다.",
      "즉시 근처에 있는 영혼 구슬을 흡수하여 짧은 시간 동안 무형 상태가 됩니다. 여제 활성화 시 추가로 투명 상태가 됩니다.",
      "파괴 가능한 천상의 눈을 장착합니다. 활성화하면 눈을 짧게 앞으로 던집니다. 눈을 본 적은 모두 시야가 제한됩니다.",
      "즉시 광란 상태가 되어 사격, 장착, 재장전 속도가 크게 증가합니다. 영혼 수확의 충전량을 무제한으로 얻습니다. 레이나가 처치하거나 레이나에게 피해를 입고 3초 이내에 죽은 적이 있으면 지속시간이 초기화됩니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Reyna/Reyna_Q.mp4", "/images/agent/HeroImages/Reyna/Reyna_E.mp4", "/images/agent/HeroImages/Reyna/Reyna_C.mp4", "/images/agent/HeroImages/Reyna/Reyna_X.mp4"],
  },
  {
    id: 12,
    name: "킬조이",
    role: "감시자",
    desc: "독일의 천재 킬조이는 덫,포탑,지뢰를 사용해 전장의 주요 위치를 확보하고 방어하는 데에 탁월합니다. 각 첨단 장비는 뒷걸음치기 바쁜 무능한 적들을 효과적으로 처리합니다.",
    agentimg: "/images/agent/HeroImages/KillJoy/KillJoy.png",
    skill: ["Q - 알람봇", "E - 포탑", "C - 나노스웜", "X - 봉쇄"],
    skillimg: ["/images/agent/HeroImages/KillJoy/KillJoy_Q.png", "/images/agent/HeroImages/KillJoy/KillJoy_E.png", "/images/agent/HeroImages/KillJoy/KillJoy_C.png", "/images/agent/HeroImages/KillJoy/KillJoy_X.png"],
    skillExplan: [
      "잠복 알람봇을 장착합니다. 발사하면 사거리 내에 들어온 적을 추적하는 봇을 배치합니다. 대상에 도달하면 봇은 폭발하여 적을 취약 상태로 만들고 피해를 입힙니다. 장착을 길게 누르면 배치된 봇을 회수합니다.",
      "포탑을 장착합니다. 발사하면 전방 180도 원뿔형 범위 안에 들어온 적을 공격하는 포탑을 배치합니다. 장착을 길게 누르면 배치된 포탑을 회수합니다.",
      "나노스웜 수류탄을 장착합니다. 발사하면 수류탄을 투척합니다. 수류탄은 지면에 닿으면 잠복 상태가 됩니다. 수류탄을 활성화하면 적에게 피해를 입히는 나노스웜을 발사합니다.",
      "봉쇄 장치를 장착합니다. 발사하면 장치를 배치합니다. 대기시간이 지나면 범위 내 탐지된 모든 적을 구속합니다. 봉쇄 장치는 적에 의해 파괴될 수 있습니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/KillJoy/KillJoy_Q.mp4", "/images/agent/HeroImages/KillJoy/KillJoy_E.mp4", "/images/agent/HeroImages/KillJoy/KillJoy_C.mp4", "/images/agent/HeroImages/KillJoy/KillJoy_X.mp4"],
  },
  {
    id: 13,
    name: "스카이",
    role: "척후대",
    desc: "호주 출신인 스카이는 야수 떼와 함께 적대적인 영역에서 길을 개척합니다. 자신의 창조물로 적을 방해하고, 치유력으로 아군을 회복시키며 든든하게 팀을 지원합니다.",
    agentimg: "/images/agent/HeroImages/Skye/Skye.png",
    skill: ["Q - 정찰자", "E - 인도하는 빛", "C - 재생", "X - 추적자"],
    skillimg: ["/images/agent/HeroImages/Skye/Skye_Q.png", "/images/agent/HeroImages/Skye/Skye_E.png", "/images/agent/HeroImages/Skye/Skye_C.png", "/images/agent/HeroImages/Skye/Skye_X.png"],
    skillExplan: [
      "태즈매니아 호랑이 장신구를 장착합니다. 발사하면 호랑이를 보내 조종합니다. 조종 중에 발사하면 전방으로 뛰어올라 폭발하며 뇌진탕을 일으키고 직접 타격한 적에게 피해를 입힙니다.",
      "매 장신구를 장착합니다. 발사하면 매를 전방으로 날립니다. 발사를 길게 누르면 조준점 방향으로 매를 유도합니다. 비행 중에 다시 사용하면 매가 섬광으로 변합니다. 섬광은 매가 날아가고 잠시 후 가장 강력해집니다.",
      "회복 장신구를 장착합니다. 발사를 길게 누르면 정신 집중하여 범위 내에서 모습이 보이는 아군들을 회복시킵니다. 회복 에너지가 바닥날 때까지 재사용할 수 있습니다. 스카이 자신이 회복할 수는 없습니다.",
      "추적자 장신구를 장착합니다. 발사하면 추적자 셋을 보내 가장 가까운 적 셋을 쫓습니다. 추적자가 표적에 다다르면 해당 적의 시야를 제한합니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Skye/Skye_Q.mp4", "/images/agent/HeroImages/Skye/Skye_E.mp4", "/images/agent/HeroImages/Skye/Skye_C.mp4", "/images/agent/HeroImages/Skye/Skye_X.mp4"],
  },
  {
    id: 14,
    name: "요루",
    role: "타격대",
    desc: "일본 출신의 요루는 발로란트 최고의 요원이고 현실에 구멍을 내어 적 진영으로 은밀히 침투합니다. 그는 공격성과 속임수를 활용해 적이 알아채기도 전에 임무를 완수합니다.",
    agentimg: "/images/agent/HeroImages/Yoru/Yoru.png",
    skill: ["Q - 기습", "E - 관문 충돌", "C - 기만", "X - 차원 표류"],
    skillimg: ["/images/agent/HeroImages/Yoru/Yoru_Q.png", "/images/agent/HeroImages/Yoru/Yoru_E.png", "/images/agent/HeroImages/Yoru/Yoru_C.png", "/images/agent/HeroImages/Yoru/Yoru_X.png"],
    skillExplan: [
      "장착하면 현실에서 불안정한 차원의 조각을 떼어냅니다. 발사하면 차원의 조각을 던집니다. 조각은 섬광을 방출하며 섬광은 단단한 표면에 닿으면 꺼집니다.",
      "균열 결속을 장착합니다. 발사하면 전방으로 결속을 날립니다. 보조 공격 시 정지 상태의 결속을 배치합니다. 활성화 시 해당 결속의 위치로 순간이동합니다. 사용 시 순간이동 흉내를 냅니다.",
      "메아리를 장착합니다. 메아리를 활성화하면 요루의 거울 형상으로 변합니다. 발사하면 거울 형상을 활성화하고 전방으로 보냅니다. 보조 공격 시 비활성화된 메아리를 배치합니다. 사용하면 비활성화된 메아리를 거울 형상으로 바꿔 전방으로 보냅니다. 적이 거울 형상을 파괴하면 섬광과 함께 폭발합니다.",
      "차원 사이를 볼 수 있는 마스크를 장착합니다. 발사하면 요루의 차원을 표류합니다. 외부의 적에게 발각되거나 영향을 받지 않습니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Yoru/Yoru_Q.mp4", "/images/agent/HeroImages/Yoru/Yoru_E.mp4", "/images/agent/HeroImages/Yoru/Yoru_C.mp4", "/images/agent/HeroImages/Yoru/Yoru_X.mp4"],
  },
  {
    id: 15,
    name: "아스트라",
    role: "전략가",
    desc: "가나 출신 요원 아스트라는 우주의 힘을 활용해 자신의 마음에 따라 전장의 모습을 바꿉니다. 천상계 형상을 자유자재로 이용하고 심도 있게 전략을 예측해 언제나 적보다 한 수 앞서 움직입니다.",
    agentimg: "/images/agent/HeroImages/Astra/Astra.png",
    skill: ["Q - 신성 파동", "E - 성운", "C - 중력의 샘", "X - 천상계 형상"],
    skillimg: ["/images/agent/HeroImages/Astra/Astra_Q.png", "/images/agent/HeroImages/Astra/Astra_E.png", "/images/agent/HeroImages/Astra/Astra_C.png", "/images/agent/HeroImages/Astra/Astra_X.png"],
    skillExplan: [
      "활성화 시 별 하나를 폭파해 신성 파동을 만들어 냅니다. 신성 파동은 짧은 충전 시간 이후 범위 내 모든 플레이어에게 뇌진탕을 일으킵니다.",
      "활성화 시 별 하나를 성운으로 변형합니다. 별은 사용 시 소멸하며, 잠시 후 다른 곳에 설치할 수 있게 됩니다. 별이 소멸하면 그 자리에 잠시 가짜 성운이 생성됩니다.",
      "활성화 시 별 하나를 중력의 샘으로 변형합니다. 중력의 샘은 범위 내 플레이어들을 끌어당기다가 폭발하며, 폭발에 닿은 플레이어들은 취약 상태가 됩니다.",
      "활성화 시 주 공격으로 별을 설치할 수 있는 천상계 형상으로 변신합니다. 이후에 별을 다시 활성화하여 신성 파동, 성운, 중력의 샘으로 바꿀 수 있습니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Astra/Astra_Q.mp4", "/images/agent/HeroImages/Astra/Astra_E.mp4", "/images/agent/HeroImages/Astra/Astra_C.mp4", "/images/agent/HeroImages/Astra/Astra_X.mp4"],
  },
  {
    id: 16,
    name: "케이/오",
    role: "척후대",
    desc: "케이/오는 레디언트를 무력화하라는 단 하나의 목적을 위해 만들어진 전쟁 병기입니다. 자신과 아군이 유리하도록 적의 스킬을 억제하여 상대의 반격 능력을 약화시킵니다.",
    agentimg: "/images/agent/HeroImages/KAYO/KAYO.png",
    skill: ["Q - 플래시/드라이브", "E - 제로/포인트", "C - 파편/탄", "X - 무력화/명령"],
    skillimg: ["/images/agent/HeroImages/KAYO/KAYO_Q.png", "/images/agent/HeroImages/KAYO/KAYO_E.png", "/images/agent/HeroImages/KAYO/KAYO_C.png", "/images/agent/HeroImages/KAYO/KAYO_X.png"],
    skillExplan: [
      "섬광탄을 장착합니다. 발사하면 투척합니다. 섬광탄은 잠시 후 폭발하며 모습이 보이는 대상을 실명시킵니다.",
      "제압용 검을 장착합니다. 발사하면 투척합니다. 검은 처음 적중한 표면에 꽂혀 잠시 후 폭발하며, 범위 내에 있는 대상을 모두 제압합니다.",
      "폭발하는 파편탄을 장착합니다. 발사하면 투척합니다. 파편탄은 바닥에 붙어 여러 차례 폭발하며, 폭발할 때마다 중심부에 있는 적에게 치명적인 피해를 입힙니다.",
      "케이/오가 즉시 양극화된 레디어나이트 에너지를 과충전하여 넓은 범위에 파동을 방출합니다. 이 파동에 맞은 적은 짧은 시간 동안 제압됩니다. 케이/오는 과충전된 동안 전투 자극제 효과를 받으며, 쓰러져도 다시 안정화할 수 있습니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/KAYO/KAYO_Q.mp4", "/images/agent/HeroImages/KAYO/KAYO_E.mp4", "/images/agent/HeroImages/KAYO/KAYO_C.mp4", "/images/agent/HeroImages/KAYO/KAYO_X.mp4"],
  },
  {
    id: 17,
    name: "체임버",
    role: "감시자",
    desc: "맵시 있는 모습으로 단단히 무장한 프랑스 무기 디자이너 체임버는 치명적인 정확도로 적을 몰아냅니다. 만일의 사태에 대한 모든 계획을 세운 그는 자신만의 커스텀 무기를 사용하여 전선을 사수하고 멀리서 적을 격퇴합니다.",
    agentimg: "/images/agent/HeroImages/Chamber/Chamber.png",
    skill: ["Q - 헤드헌터", "E - 랑데부", "C - 트레이드마크", "X - 역작"],
    skillimg: ["/images/agent/HeroImages/Chamber/Chamber_Q.png", "/images/agent/HeroImages/Chamber/Chamber_E.png", "/images/agent/HeroImages/Chamber/Chamber_C.png", "/images/agent/HeroImages/Chamber/Chamber_X.png"],
    skillExplan: [
      "활성화하면 헤비 피스톨을 장착합니다. 장착한 피스톨로 보조 공격하면 조준 사격합니다.",
      "순간이동 앵커를 설치합니다. 지면에서 앵커 범위 내에 있을 때 다시 활성화하면 앵커로 빠르게 순간 이동합니다. 앵커는 회수하여 재배치할 수 있습니다.",
      "적을 스캔하는 함정을 배치합니다. 시야에 보이는 적이 사거리 안에 들어오면 함정이 카운트다운 후 주변 지형을 불안하게 만들고 일정 시간 유지되는 둔화 영역을 생성하여 영역에 있는 플레이어의 속도를 늦춥니다. 함정은 회수하여 재배치할 수 있습니다.",
      "활성화하면 상체 직격 시 적을 처치할 수 있는 강력한 커스텀 저격총을 소환합니다. 적을 처치하면 일정 시간 유지되는 둔화 영역을 생성하여 영역에 있는 플레이어의 속도를 늦춥니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Chamber/Chamber_Q.mp4", "/images/agent/HeroImages/Chamber/Chamber_E.mp4", "/images/agent/HeroImages/Chamber/Chamber_C.mp4", "/images/agent/HeroImages/Chamber/Chamber_X.mp4"],
  },
  {
    id: 18,
    name: "네온",
    role: "타격대",
    desc: "필리핀 출신 요원 네온은 엄청난 속도로 달리며 몸에서 만들어낸 생체 전기를 빠르게 방출시킵니다. 네온은 빠르게 움직여 방심한 적을 기습하고, 번개보다 빠르게 제압합니다.",
    agentimg: "/images/agent/HeroImages/Neon/Neon.png",
    skill: ["Q - 릴레이 볼트", "E - 고속 기어", "C - 추월 차선", "X - 오버드라이브"],
    skillimg: ["/images/agent/HeroImages/Neon/Neon_Q.png", "/images/agent/HeroImages/Neon/Neon_E.png", "/images/agent/HeroImages/Neon/Neon_C.png", "/images/agent/HeroImages/Neon/Neon_X.png"],
    skillExplan: [
      "한 번 튕기는 에너지 볼트를 즉시 투척합니다. 볼트는 표면에 맞을 때마다 지면에 전류를 흘려보내 뇌진탕을 일으킵니다.",
      "네온의 힘을 즉시 집중해 속도를 높입니다. 충전되면 보조 공격 시 전기 슬라이드를 발동합니다. 슬라이드 충전량은 2킬마다 초기화됩니다.",
      "전방의 지면에 에너지로 이루어진 선 두 개를 발사합니다. 선은 짧은 거리만큼 늘어나고 표면에 적중하면 멈춥니다. 선은 솟아나 정전기 벽이 되어 시야를 차단합니다.",
      "짧은 시간 동안 네온의 모든 힘과 속도를 해방합니다. 발사하면 힘을 집중해 이동 정확도가 높은 치명적인 번개 광선을 만들어냅니다. 지속시간은 킬할 때마다 초기화됩니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Neon/Neon_Q.mp4", "/images/agent/HeroImages/Neon/Neon_E.mp4", "/images/agent/HeroImages/Neon/Neon_C.mp4", "/images/agent/HeroImages/Neon/Neon_X.mp4"],
  },
  {
    id: 19,
    name: "페이드",
    role: "척후대",
    desc: "튀르키예 출신 현상금 사냥꾼 페이드는 악몽의 힘을 이용해 적의 비밀을 캐냅니다. 공포와 하나가 되어 표적을 쫓고 마음속 가장 깊은 곳에 숨겨진 공포를 파헤친 뒤, 어둠 속에서 짓밟습니다.",
    agentimg: "/images/agent/HeroImages/Fade/Fade.png",
    skill: ["Q - 포박", "E - 귀체", "C - 추적귀", "X - 황혼"],
    skillimg: ["/images/agent/HeroImages/Fade/Fade_Q.png", "/images/agent/HeroImages/Fade/Fade_E.png", "/images/agent/HeroImages/Fade/Fade_C.png", "/images/agent/HeroImages/Fade/Fade_X.png"],
    skillExplan: [
      "악몽의 먹물 구슬을 장착합니다. 발사하면 일정 시간이 지난 후 땅에 떨어지는 구슬을 던집니다. 구슬이 땅에 닿으면 먹물이 폭발해 적이 일반적인 방법으로는 빠져나갈 수 없는 구역을 생성합니다. 스킬을 다시 사용하면 구슬을 일찍 떨어뜨립니다.",
      "악몽의 실체를 장착합니다. 발사하면 일정 시간이 지난 후 땅에 떨어지는 구슬을 던집니다. 구슬이 땅에 닿으면 시야에 들어온 적의 위치를 드러내는 악몽의 실체로 변합니다. 적은 악몽의 실체를 파괴할 수 있습니다. 스킬을 다시 사용하면 구슬을 일찍 떨어뜨립니다.",
      "추적귀를 장착합니다. 발사하면 직선으로 이동하는 추적귀를 내보냅니다. 추적귀는 전방 원뿔 시야 범위에 들어온 적이나 흔적에 고정되어 추격하며, 닿으면 적의 시야를 제한합니다. 발사 버튼을 길게 누르면 추적귀를 조준점 방향으로 움직일 수 있습니다.",
      "공포의 힘을 장착합니다. 발사하면 벽을 통과하는 악몽의 에너지 파동을 보냅니다. 에너지가 적에게 닿으면 흔적을 남기며 청력을 약화시키고 부패 효과를 적용합니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Fade/Fade_Q.mp4", "/images/agent/HeroImages/Fade/Fade_E.mp4", "/images/agent/HeroImages/Fade/Fade_C.mp4", "/images/agent/HeroImages/Fade/Fade_X.mp4"],
  },
  {
    id: 20,
    name: "하버",
    role: "전략가",
    desc: "가나 출신 요원 아스트라는 우주의 힘을 활용해 자신의 마음에 따라 전장의 모습을 바꿉니다. 천상계 형상을 자유자재로 이용하고 심도 있게 전략을 예측해 언제나 적보다 한 수 앞서 움직입니다.",
    agentimg: "/images/agent/HeroImages/Harbor/Harbor.png",
    skill: ["Q - 해만", "E - 만조", "C - 폭포", "X - 심판"],
    skillimg: ["/images/agent/HeroImages/Harbor/Harbor_Q.png", "/images/agent/HeroImages/Harbor/Harbor_E.png", "/images/agent/HeroImages/Harbor/Harbor_C.png", "/images/agent/HeroImages/Harbor/Harbor_X.png"],
    skillExplan: [
      "방어용 물 구체를 장착합니다. 발사하면 투척합니다. 보조 공격 시 낮게 투척합니다. 땅에 닿으면 탄환을 막는 물의 보호막이 생성됩니다. 이 보호막은 파괴할 수 있습니다.",
      "물의 장벽을 장착합니다. 발사하면 지면을 따라 물을 앞으로 보냅니다. 발사를 길게 누르면 조준점 방향으로 물을 유도합니다. 물은 지형을 통과하며 지나가는 길에 장벽을 생성합니다. 유도 중 보조 공격 시 물이 일찍 멈춥니다. 맞은 플레이어는 둔화됩니다.",
      "물의 파동을 장착합니다. 발사하면 벽을 통과하는 파동을 앞으로 보냅니다. 다시 사용하면 파동이 멈춥니다. 맞은 플레이어는 둔화됩니다.",
      "유물의 모든 힘을 장착합니다. 발사하면 지면에 간헐천을 소환합니다. 해당 지역 내에 있는 적 플레이어는 잇따른 간헐천 분출의 표적이 됩니다. 분출에 맞은 플레이어에게 뇌진탕을 일으킵니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Harbor/Harbor_Q.mp4", "/images/agent/HeroImages/Harbor/Harbor_E.mp4", "/images/agent/HeroImages/Harbor/Harbor_C.mp4", "/images/agent/HeroImages/Harbor/Harbor_X.mp4"],
  },
  {
    id: 21,
    name: "게코",
    role: "척후대",
    desc: "로스앤젤레스 출신 게코는 무시무시한 봇 생명체[7]들을 이끕니다. 봇들이 돌진해 적들을 분산시키면 게코가 따라가 진열을 재정비한 후 다시 공격을 개시합니다.",
    agentimg: "/images/agent/HeroImages/Gekko/Gekko.png",
    skill: ["Q - 지원봇", "E - 기절봇", "C - 폭파봇 지옥", "X - 요동봇"],
    skillimg: ["/images/agent/HeroImages/Gekko/Gekko_Q.png", "/images/agent/HeroImages/Gekko/Gekko_E.png", "/images/agent/HeroImages/Gekko/Gekko_C.png", "/images/agent/HeroImages/Gekko/Gekko_X.png"],
    skillExplan: [
      "지원봇을 장착합니다. 발사하면 지원봇을 앞으로 보내 적을 찾습니다. 지원봇은 처음 본 적에게 뇌진탕을 유발합니다. 스파이크 지점이나 설치된 스파이크를 겨눈 상태에서 보조 공격 시 지원봇에게 스파이크 설치나 해제를 명령할 수 있습니다. 설치하려면 게코가 스파이크를 소지하고 있어야 합니다.",
      "기절봇을 장착합니다. 발사하면 기절봇이 공중으로 솟아오릅니다. 기절봇은 승천한 뒤 시야에 들어온 적을 향해 플라즈마 폭발을 일으킵니다. 플라즈마에 맞은 적을 실명합니다.",
      "지원봇을 장착합니다. 발사하면 지원봇을 앞으로 보내 적을 찾습니다. 지원봇은 처음 본 적에게 뇌진탕을 유발합니다. 스파이크 지점이나 설치된 스파이크를 겨눈 상태에서 보조 공격 시 지원봇에게 스파이크 설치나 해제를 명령할 수 있습니다. 설치하려면 게코가 스파이크를 소지하고 있어야 합니다.",
      "요동봇을 장착합니다. 발사하면 요동봇과 정신이 연결되어 요동봇을 적 진영으로 조종합니다. 활성화하면 앞으로 돌진해 폭발하며 좁은 범위 안에 있는 모든 적을 구속합니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Gekko/Gekko_Q.mp4", "/images/agent/HeroImages/Gekko/Gekko_E.mp4", "/images/agent/HeroImages/Gekko/Gekko_C.mp4", "/images/agent/HeroImages/Gekko/Gekko_X.mp4"],
  },
  {
    id: 22,
    name: "데드록",
    role: "감시자",
    desc: "노르웨이 출신 요원 데드록은 최첨단 나노와이어를 배치해 전장의 위협적인 공격을 막아냅니다. 누구도 데드록의 감시를 피할 수도, 집요한 공격에서 살아남을 수도 없습니다.",
    agentimg: "/images/agent/HeroImages/Deadlock/Deadlock.png",
    skill: ["Q - 음향 센서", "E - 장벽망", "C - 중력그물", "X - 소멸"],
    skillimg: ["/images/agent/HeroImages/Deadlock/Deadlock_Q.png", "/images/agent/HeroImages/Deadlock/Deadlock_E.png", "/images/agent/HeroImages/Deadlock/Deadlock_C.png", "/images/agent/HeroImages/Deadlock/Deadlock_X.png"],
    skillExplan: [
      "음향 센서를 장착합니다. 발사하면 음향 센서를 설치합니다. 센서는 지역에서 적이 내는 소리를 탐지합니다. 발걸음 소리, 사격음, 큰 소음이 탐지되면 지역에 뇌진탕을 일으킵니다.",
      "장벽망 디스크를 장착합니다. 발사하면 디스크를 앞으로 던집니다. 디스크가 지면에 닿으면 해당 지점에 장벽이 생성되어 캐릭터가 움직이지 못하도록 억제합니다.",
      "중력그물 수류탄을 장착합니다. 발사하면 수류탄을 투척합니다. 보조 공격 시 수류탄을 높이 던집니다. 중력그물 수류탄은 지면에 닿으면 폭발해 범위 내에 있는 모든 적을 앉아서 천천히 움직이게 합니다.",
      "나노와이어 가속기를 장착합니다. 발사하면 처음 적중한 적을 생포하는 나노와이어 펄스를 발사합니다. 생포된 적은 나노와이어의 경로를 따라 끌려가며, 끝에 도달하기 전에 풀려나지 않으면 사망합니다. 나노와이어 고치는 파괴할 수 있습니다.",
    ],
    skillvideo: ["/images/agent/HeroImages/Deadlock/Deadlock_Q.mp4", "/images/agent/HeroImages/Deadlock/Deadlock_E.mp4", "/images/agent/HeroImages/Deadlock/Deadlock_C.mp4", "/images/agent/HeroImages/Deadlock/Deadlock_X.mp4"],
  },
];
