export const products = [
  {
    id: 1,
    title: "2023 발로란트 마스터 총기장식 열쇠고리",
    price: 22000,
    category: "acc",
    image: "/images/goods/accessory1_1.jpg",
    subimage: "/images/goods/accessory1_2.jpg",
  },
  {
    id: 2,
    title: "2023 발로란트 마스터스 랭크 업! 후드티",
    price: 149000,
    category: "clothes",
    image: "/images/goods/clothes1_1.jpg",
    subimage: "/images/goods/clothes1_2.jpg",
  },
  {
    id: 3,
    title: "2023 발로란트 마스터스 도쿄 반팔티",
    price: 49000,
    category: "clothes",
    image: "/images/goods/clothes2_1.jpg",
    subimage: "/images/goods/clothes2_2.jpg",
  },
  {
    id: 4,
    title: "2023 발로란트 마스터스 겉옷 가디건",
    price: 210000,
    category: "clothes",
    image: "/images/goods/clothes3_1.jpg",
    subimage: "/images/goods/clothes3_2.jpg",
  },
  {
    id: 5,
    title: "발로란트 제트 마우스 패드",
    price: 25000,
    category: "acc",
    image: "/images/goods/accessory2_1.jpg",
    subimage: "/images/goods/accessory2_2.jpg",
  },
  {
    id: 6,
    title: "발로란트 전략가 곰 인형",
    price: 39000,
    category: "doll",
    image: "/images/goods/doll1_1.jpg",
    subimage: "/images/goods/doll1_2.jpg",
  },
  {
    id: 7,
    title: "True Damage 투어 후드티",
    price: 79000,
    category: "clothes",
    image: "/images/goods/clothes4_1.jpg",
    subimage: "/images/goods/clothes4_2.jpg",
  },
  {
    id: 8,
    title: "발로란트 제트 단검 목걸이",
    price: 90000,
    category: "acc",
    image: "/images/goods/accessory3_1.jpg",
    subimage: "/images/goods/accessory3_2.png",
  },
  {
    id: 9,
    title: "발로란트 제트 스태츄",
    price: 210000,
    category: "figure",
    image: "/images/goods/figure1_1.png",
    subimage: "/images/goods/figure1_2.png",
  },
  {
    id: 10,
    title: "발로란트 피닉스 스태츄",
    price: 210000,
    category: "figure",
    image: "/images/goods/figure2_1.png",
    subimage: "/images/goods/figure2_2.png",
  },
  {
    id: 11,
    title: "2022 월드 챔피언십 장로 드래곤 인형",
    price: 45000,
    category: "doll",
    image: "/images/goods/doll2_1.jpg",
    subimage: "/images/goods/doll2_2.jpg",
  },
  {
    id: 12,
    title: "발로란트 피닉스 마우스 패드",
    price: 25000,
    category: "acc",
    image: "/images/goods/accessory4_1.jpg",
    subimage: "/images/goods/accessory4_2.jpg",
  },
  {
    id: 13,
    title: "요루 페이드 아크릴 데스크탑 장식",
    price: 32000,
    category: "figure",
    image: "/images/goods/figure3_1.jpg",
    subimage: "/images/goods/figure3_2.jpg",
  },
  {
    id: 14,
    title: "발로란트 심술 두꺼비 인형",
    price: 38000,
    category: "doll",
    image: "/images/goods/doll3_1.jpg",
    subimage: "/images/goods/doll3_2.jpg/",
  },
  {
    id: 15,
    title: "발로란트 전투 토끼 인형",
    price: 42000,
    category: "doll",
    image: "/images/goods/doll4_1.jpg",
    subimage: "/images/goods/doll4_2.jpg",
  },
  {
    id: 16,
    title: "체임버 소바 아크릴 데스크탑 장식",
    price: 25000,
    category: "figure",
    image: "/images/goods/figure4_1.jpg",
    subimage: "/images/goods/figure4_2.jpg",
  },
];
